name: flutter_rounded_progress_bar
description: Rounded Progressbar in Flutter that customize color and border.
version: 0.1.3
author: benznest <benz7nbet@gmail.com>
homepage: https://github.com/benznest/flutter_rounded_progress_bar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
